name: "Test tutorials"
description: "Test turials"
inputs:
  python-version:
    description: "Which Python version to run on"
    required: true
runs:
  using: "composite"
  steps:
    ### Setup prerequisites
    - name: Set up uv
      shell: bash
      # Install a specific uv version using the installer
      run: curl -LsSf https://astral.sh/uv/0.4.0/install.sh | sh

    - name: Set up Python
      shell: bash
      run: uv python install

    # Installing
    - name: Install dependencies
      shell: bash
      run: |
        make install-tutorials

    ### Run tests
    - name: Compile notebooks and check for errors
      shell: bash
      run: |
        make test-tutorials
        for notebook in tutorials/*.ipynb; do
          if grep -q "\"cell_type\": \"error\"" $notebook; then
            echo "Error cell found in $notebook"
            exit 1
          fi
        done
