name: "Test tutorials"
description: "Test turials"
inputs:
  python-version:
    description: "Which Python version to run on"
    required: true
    default: 3.9
  poetry-version:
    description: "Which version of Poetry to install"
    default: 1.1.15
  cache-version:
    description: "Cache version for invalidation"
    default: 0.0.0

runs:
  using: "composite"
  steps:
    ### Setup prerequisites
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    ### Caching
    - name: Cache poetry and venv
      id: cache-poetry-and-venv
      uses: MartinBernstorff/cache-poetry-and-venv@latest
      with:
        poetry-version: ${{ inputs.poetry-version }}
        cache-version: ${{ inputs.cache-version }}
        python-version: ${{ inputs.python-version }}

    # Installing
    - name: Install Poetry
      if: steps.cache-poetry-and-venv.outputs.poetry-cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install Project
      if: steps.cache-poetry-and-venv.outputs.venv-cache-hit != 'true'
      shell: bash
      run: poetry install -vvv

    ### Run tests
    - name: Install jupyter
      shell: bash
      run: |
        pip install jupyter
    - name: Compile notebooks and check for errors
      shell: bash
      run: |
        poetry run jupyter nbconvert --to notebook --execute tutorials/*.ipynb
        for notebook in tutorials/*.ipynb; do
          if grep -q "\"cell_type\": \"error\"" $notebook; then
            echo "Error cell found in $notebook"
            exit 1
          fi
        done
