name: "Test tutorials"
description: "Test turials"
inputs:
  python-version:
    description: "Which Python version to run on"
    required: true
    default: "3.9"
runs:
  using: "composite"
  steps:
    ### Setup prerequisites
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    # Installing
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,text,tutorials]"

    ### Run tests
    - name: Install jupyter
      shell: bash
      run: |
        pip install jupyter
    - name: Compile notebooks and check for errors
      shell: bash
      run: |
        jupyter nbconvert --to notebook --execute docs/tutorials/*.ipynb
        for notebook in tutorials/*.ipynb; do
          if grep -q "\"cell_type\": \"error\"" $notebook; then
            echo "Error cell found in $notebook"
            exit 1
          fi
        done
